/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import com.example.demo.model.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>sample_db</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_IDX_PREF = Indexes0.USER_IDX_PREF;
    public static final Index USER_IDX_SEX = Indexes0.USER_IDX_SEX;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_IDX_PREF = Internal.createIndex("idx_pref", User.USER, new OrderField[] { User.USER.PREFECTURE_ID }, false);
        public static Index USER_IDX_SEX = Internal.createIndex("idx_sex", User.USER, new OrderField[] { User.USER.SEX }, false);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
