/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import com.example.demo.model.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleDb extends SchemaImpl {

    private static final long serialVersionUID = 2053819077;

    /**
     * The reference instance of <code>sample_db</code>
     */
    public static final SampleDb SAMPLE_DB = new SampleDb();

    /**
     * ユーザーテーブル
     */
    public final User USER = com.example.demo.model.tables.User.USER;

    /**
     * No further instances allowed
     */
    private SampleDb() {
        super("sample_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
