/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model;


import com.example.demo.model.tables.User;


/**
 * Convenience access to all tables in sample_db
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * ユーザーテーブル
     */
    public static final User USER = com.example.demo.model.tables.User.USER;
}
