/*
 * This file is generated by jOOQ.
 */
package com.example.demo.model.tables.records;


import com.example.demo.converter.Prefecture;
import com.example.demo.converter.Sex;
import com.example.demo.model.tables.User;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ユーザーテーブル
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record8<Long, String, Sex, Prefecture, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 386302298;

    /**
     * Setter for <code>sample_db.user.id</code>. ユーザーID
     */
    public UserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.id</code>. ユーザーID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sample_db.user.nick_name</code>. ニックネーム
     */
    public UserRecord setNickName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.nick_name</code>. ニックネーム
     */
    public String getNickName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sample_db.user.sex</code>. 性別 M:男性 F:女性
     */
    public UserRecord setSex(Sex value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.sex</code>. 性別 M:男性 F:女性
     */
    public Sex getSex() {
        return (Sex) get(2);
    }

    /**
     * Setter for <code>sample_db.user.prefecture_id</code>. 都道府県 0:不明、1:北海道 - 8:九州・沖縄
     */
    public UserRecord setPrefectureId(Prefecture value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.prefecture_id</code>. 都道府県 0:不明、1:北海道 - 8:九州・沖縄
     */
    public Prefecture getPrefectureId() {
        return (Prefecture) get(3);
    }

    /**
     * Setter for <code>sample_db.user.email</code>. メールアドレス
     */
    public UserRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.email</code>. メールアドレス
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sample_db.user.memo</code>. 備考欄
     */
    public UserRecord setMemo(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.memo</code>. 備考欄
     */
    public String getMemo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sample_db.user.create_at</code>.
     */
    public UserRecord setCreateAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>sample_db.user.update_at</code>.
     */
    public UserRecord setUpdateAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sample_db.user.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Sex, Prefecture, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Sex, Prefecture, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.NICK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Sex> field3() {
        return User.USER.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Prefecture> field4() {
        return User.USER.PREFECTURE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return User.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return User.USER.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return User.USER.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return User.USER.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sex component3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Prefecture component4() {
        return getPrefectureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sex value3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Prefecture value4() {
        return getPrefectureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setNickName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(Sex value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(Prefecture value) {
        setPrefectureId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Long value1, String value2, Sex value3, Prefecture value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String nickName, Sex sex, Prefecture prefectureId, String email, String memo, LocalDateTime createAt, LocalDateTime updateAt) {
        super(User.USER);

        set(0, id);
        set(1, nickName);
        set(2, sex);
        set(3, prefectureId);
        set(4, email);
        set(5, memo);
        set(6, createAt);
        set(7, updateAt);
    }
}
